# Generated by Django 5.0 on 2025-12-04 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0009_skillhistory'),
        ('waitlist_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='waitlist_data.doctrinecategory')),
            ],
            options={
                'verbose_name_plural': 'Doctrine Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctrineFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eft_format', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_doctrinal', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='waitlist_data.doctrinecategory')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctrines', to='pilot_data.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='FitModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('slot', models.CharField(choices=[('high', 'High Slot'), ('mid', 'Mid Slot'), ('low', 'Low Slot'), ('rig', 'Rig Slot'), ('subsystem', 'Subsystem'), ('drone', 'Drone Bay'), ('cargo', 'Cargo')], default='cargo', max_length=20)),
                ('fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='waitlist_data.doctrinefit')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot_data.itemtype')),
            ],
        ),
    ]
