# Generated by Django 5.0 on 2025-12-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0002_doctrinecategory_doctrinefit_fitmodule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctrinefit',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='doctrinefit',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
