# Generated by Django 5.0 on 2025-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0003_alter_doctrinefit_options_doctrinefit_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('style_classes', models.CharField(default='bg-slate-700 text-slate-300 border-slate-600', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='doctrinefit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fits', to='waitlist_data.doctrinetag'),
        ),
    ]
