# Generated by Django 5.0 on 2025-12-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0013_typeeffect'),
        ('waitlist_data', '0004_doctrinetag_doctrinefit_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='esi_fleet_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'X-Up (Pending)'), ('approved', 'Approved'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='pilot_data.evecharacter')),
                ('fit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_entries', to='waitlist_data.doctrinefit')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='waitlist_data.fleet')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
