# Generated by Django 5.0 on 2025-12-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0005_fleet_esi_fleet_id_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='raw_eft',
            field=models.TextField(blank=True, default=''),
        ),
    ]
