# Generated by Django 5.0 on 2025-12-07 09:44

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Fleet = apps.get_model('waitlist_data', 'Fleet')
    for row in Fleet.objects.all():
        row.join_token = uuid.uuid4()
        row.save(update_fields=['join_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0006_waitlistentry_raw_eft'),
    ]

    operations = [
        # 1. Add field as nullable first
        migrations.AddField(
            model_name='fleet',
            name='join_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # 2. Populate existing rows with unique UUIDs
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        
        # 3. Alter field to be unique and not null
        migrations.AlterField(
            model_name='fleet',
            name='join_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]