# Generated by Django 5.0 on 2025-12-09 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0016_evecharacter_x_up_visible'),
        ('waitlist_data', '0007_fleet_join_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FleetActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('x_up', 'X-Up (Joined Waitlist)'), ('approved', 'Approved by FC'), ('denied', 'Denied by FC'), ('invited', 'Invited to Fleet'), ('esi_join', 'Detected In-Game (Bypassed Waitlist)'), ('left_waitlist', 'Left Waitlist'), ('left_fleet', 'Left Fleet (In-Game)'), ('fit_update', 'Updated Fit'), ('promoted', 'Promoted (Wing/Squad Cmd)'), ('demoted', 'Demoted'), ('kicked', 'Kicked from Fleet')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ship_name', models.CharField(blank=True, max_length=100)),
                ('hull_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_history', to='pilot_data.evecharacter')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='waitlist_data.fleet')),
            ],
            options={
                'verbose_name_plural': 'Fleet Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
