# Generated by Django 5.0 on 2025-12-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0008_fleet_end_time_fleetactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetactivity',
            name='action',
            field=models.CharField(choices=[('x_up', 'X-Up (Joined Waitlist)'), ('approved', 'Approved by FC'), ('denied', 'Denied by FC'), ('invited', 'Invited to Fleet'), ('esi_join', 'Joined Fleet (In-Game)'), ('left_waitlist', 'Left Waitlist'), ('left_fleet', 'Left Fleet (In-Game)'), ('fit_update', 'Updated Fit'), ('moved', 'Position Changed'), ('promoted', 'Promoted'), ('demoted', 'Demoted'), ('kicked', 'Kicked from Fleet')], max_length=20),
        ),
    ]
