# Generated by Django 5.0 on 2025-12-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0009_alter_fleetactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetactivity',
            name='fit_eft',
            field=models.TextField(blank=True, null=True),
        ),
    ]
