# Generated by Django 5.0 on 2025-12-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0016_evecharacter_x_up_visible'),
        ('waitlist_data', '0011_alter_fleetactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='hull',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries_hull', to='pilot_data.itemtype'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='fit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_entries', to='waitlist_data.doctrinefit'),
        ),
    ]
