# Generated by Django 5.0 on 2025-12-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0016_evecharacter_x_up_visible'),
        ('waitlist_data', '0012_waitlistentry_hull_alter_waitlistentry_fit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetStructureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Setup', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_templates', to='pilot_data.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='StructureWing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='waitlist_data.fleetstructuretemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StructureSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='waitlist_data.structurewing')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
