# Generated by Django 5.0 on 2025-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0013_fleetstructuretemplate_structurewing_structuresquad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='motd',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fleetstructuretemplate',
            name='default_motd',
            field=models.TextField(blank=True, default=''),
        ),
    ]
