# Generated by Django 5.0 on 2025-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0014_fleet_motd_fleetstructuretemplate_default_motd'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinecategory',
            name='target_column',
            field=models.CharField(choices=[('logi', 'Logistics'), ('dps', 'DPS'), ('sniper', 'Sniper'), ('other', 'Other')], default='other', help_text='Which column should fits in this category appear in on the dashboard?', max_length=20),
        ),
    ]
