# Generated by Django 5.0 on 2025-12-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0015_doctrinecategory_target_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinecategory',
            name='target_column',
            field=models.CharField(choices=[('inherit', 'Inherit from Parent'), ('logi', 'Logistics'), ('dps', 'DPS'), ('sniper', 'Sniper'), ('other', 'Other')], default='inherit', help_text="Which column should fits in this category appear in? Select 'Inherit' to use the parent category's setting.", max_length=20),
        ),
    ]
