# Generated by Django 5.0 on 2025-12-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist_data', '0016_alter_doctrinecategory_target_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinecategory',
            name='target_column',
            field=models.CharField(choices=[('inherit', 'Inherit (Child Priority)'), ('logi', 'Logistics'), ('dps', 'DPS'), ('sniper', 'Sniper'), ('other', 'Other')], default='inherit', help_text="Where should ships in this category appear? 'Inherit' checks specific child settings first, then bubbles up to parent.", max_length=20),
        ),
    ]
