# Generated by Django 5.0 on 2025-12-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0018_corpwalletjournal_custom_category_and_more'),
        ('waitlist_data', '0017_alter_doctrinecategory_target_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seconds', models.BigIntegerField(default=0)),
                ('hull_stats', models.JSONField(blank=True, default=dict)),
                ('active_session_start', models.DateTimeField(blank=True, null=True)),
                ('active_hull', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pilot_data.evecharacter')),
            ],
        ),
    ]
