# Generated by Django 5.0 on 2025-12-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0018_corpwalletjournal_custom_category_and_more'),
        ('waitlist_data', '0018_characterstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='can_fly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('doctrine_fit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='waitlist_data.doctrinefit')),
                ('hull', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='pilot_data.itemtype')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_fits', to='pilot_data.itemtype')),
            ],
            options={
                'ordering': ['skill__type_name'],
            },
        ),
    ]
