# Generated by Django 5.0 on 2025-12-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0018_corpwalletjournal_custom_category_and_more'),
        ('waitlist_data', '0019_waitlistentry_can_fly_waitlistentry_missing_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Higher number = Higher priority check.')),
                ('badge_class', models.CharField(default='bg-yellow-500/20 text-yellow-400 border-yellow-500/50', help_text='Tailwind CSS classes for the badge.', max_length=100)),
                ('hex_color', models.CharField(default='#EAB308', help_text='Hex color for glowing effects.', max_length=7)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.AlterModelOptions(
            name='skillrequirement',
            options={'ordering': ['skill__type_name', 'group__name']},
        ),
        migrations.AlterField(
            model_name='skillrequirement',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='skillrequirement',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_for_fits', to='pilot_data.itemtype'),
        ),
        migrations.AddField(
            model_name='skillrequirement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='waitlist_data.skillgroup'),
        ),
        migrations.AddField(
            model_name='skillrequirement',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='waitlist_data.skilltier'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waitlist_data.skilltier'),
        ),
        migrations.CreateModel(
            name='SkillGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='waitlist_data.skillgroup')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot_data.itemtype')),
            ],
            options={
                'ordering': ['skill__type_name'],
                'unique_together': {('group', 'skill')},
            },
        ),
    ]
