# Generated by Django 5.0 on 2025-12-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "waitlist_data",
            "0020_skillgroup_skilltier_alter_skillrequirement_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
