# Generated by Django 5.0 on 2025-12-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Internal identifier used in code checks (e.g. 'fleet_command')", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='capabilities', to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Capabilities',
                'ordering': ['category', 'name'],
            },
        ),
    ]
