# Generated by Django 5.0 on 2025-12-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(db_index=True, default=999)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_config', to='auth.group')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
