# Generated by Django 5.0 on 2025-12-11 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ban_banauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="expiration_logged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ban",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="banauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Ban Created"),
                    ("update", "Ban Updated"),
                    ("remove", "Ban Removed"),
                    ("expire", "Ban Expired"),
                ],
                max_length=20,
            ),
        ),
    ]
