# Generated by Django 5.0 on 2025-12-11 05:31

from django.db import migrations

# Copied from core/utils.py to ensure migration is self-contained
ROLE_HIERARCHY_DEFAULT = [
    'Admin',
    'Leadership',
    'Officer',
    'Certified Trainer',
    'Training CT',
    'Fleet Commander',
    'Training FC',
    'Assault FC',
    'Line Commander',
    'Resident',
    'Public'
]

ROLES_ADMIN = ['Admin']

ROLES_FC = [
    'Admin', 'Leadership', 'Officer', 'Certified Trainer', 'Training CT',
    'Fleet Commander', 'Training FC', 'Assault FC'
]

ROLES_MANAGEMENT = ROLE_HIERARCHY_DEFAULT[:10]

SYSTEM_CAPABILITIES = [
    {"category": "System Administration", "name": "Full System Access", "desc": "Manage SDE, Roles, System Health, Unlink Alts.", "roles": ROLES_ADMIN},
    {"category": "System Administration", "name": "Manage Doctrines", "desc": "Create, Edit, and Delete Doctrine Fits.", "roles": ROLES_ADMIN},
    {"category": "System Administration", "name": "Promote/Demote Users", "desc": "Assign roles to users (up to own rank) and Unlink Alts.", "roles": ROLES_ADMIN},
    {"category": "System Administration", "name": "Manage Analysis Rules", "desc": "Configure item comparison logic (Higher/Lower is Better).", "roles": ROLES_ADMIN},
    {"category": "System Administration", "name": "View Sensitive Data", "desc": "View unobfuscated financial data in pilot profiles.", "roles": ['Admin']},

    {"category": "SRP & Finance", "name": "Manage SRP Source", "desc": "Configure the SRP data source character and settings.", "roles": ['Admin', 'Leadership']},
    {"category": "SRP & Finance", "name": "View SRP Dashboard", "desc": "Access the SRP Wallet History and Analytics page.", "roles": ['Admin', 'Leadership', 'Officer']},

    {"category": "User Management", "name": "Manage Bans", "desc": "Ban and unban users from accessing the waitlist and dashboard.", "roles": ROLES_ADMIN + ROLES_MANAGEMENT},
    {"category": "User Management", "name": "View Ban Audit Log", "desc": "View the audit log of ban actions.", "roles": ROLES_ADMIN},

    {"category": "Fleet Operations", "name": "Fleet Command", "desc": "Create/Close Fleets, Take Command, FC Actions (Approve/Invite).", "roles": ROLES_FC},
    {"category": "Fleet Operations", "name": "Inspect Pilots", "desc": "View full pilot details (Skills, Assets) in User Search.", "roles": ROLES_FC},
    {"category": "Fleet Operations", "name": "View Fleet Overview", "desc": "See the live fleet composition sidebar on the dashboard.", "roles": ROLES_MANAGEMENT},
    {"category": "General", "name": "Management Access", "desc": "Access the Management Dashboard (limited view).", "roles": ROLES_MANAGEMENT},
    {"category": "General", "name": "Join Waitlists", "desc": "X-Up for fleets.", "roles": ROLE_HIERARCHY_DEFAULT}
]

def create_capabilities(apps, schema_editor):
    Capability = apps.get_model('core', 'Capability')
    Group = apps.get_model('auth', 'Group')

    for cap_data in SYSTEM_CAPABILITIES:
        slug = cap_data['name'].lower().replace(' ', '_').replace('/', '_')
        cap, created = Capability.objects.update_or_create(
            slug=slug,
            defaults={
                'name': cap_data['name'],
                'description': cap_data['desc'],
                'category': cap_data['category']
            }
        )

        # Assign to Roles
        for role_name in cap_data['roles']:
            group, _ = Group.objects.get_or_create(name=role_name)
            cap.groups.add(group)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ban_expiration_logged_alter_ban_user_and_more"),
    ]

    operations = [
        migrations.RunPython(create_capabilities),
    ]
