# Generated by Django 5.0 on 2025-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_ban_capabilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'ordering': ['order', 'category', 'name'], 'verbose_name_plural': 'Capabilities'},
        ),
        migrations.AddField(
            model_name='capability',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in the permissions matrix'),
        ),
    ]
