# Generated by Django 5.0 on 2025-11-23 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('capacity', models.FloatField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('market_group_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EveCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(unique=True)),
                ('character_name', models.CharField(max_length=255)),
                ('corporation_id', models.BigIntegerField(default=0)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
