# Generated by Django 5.0 on 2025-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='alliance_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='corporation_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='current_ship_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='current_ship_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='total_sp',
            field=models.BigIntegerField(default=0),
        ),
    ]
