# Generated by Django 5.0 on 2025-11-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0002_evecharacter_access_token_evecharacter_alliance_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
