# Generated by Django 5.0 on 2025-11-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0003_itemgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_history', to='pilot_data.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterImplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implants', to='pilot_data.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.IntegerField()),
                ('finished_level', models.IntegerField()),
                ('queue_position', models.IntegerField()),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_queue', to='pilot_data.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.IntegerField()),
                ('active_skill_level', models.IntegerField()),
                ('skillpoints_in_skill', models.BigIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pilot_data.evecharacter')),
            ],
        ),
    ]
