# Generated by Django 5.0 on 2025-11-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0004_characterhistory_characterimplant_characterqueue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiHeaderCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(db_index=True, max_length=100)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esi_headers', to='pilot_data.evecharacter')),
            ],
            options={
                'unique_together': {('character', 'endpoint_name')},
            },
        ),
    ]
