# Generated by Django 5.0 on 2025-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0005_esiheadercache'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterhistory',
            name='corporation_name',
            field=models.CharField(blank=True, default='Unknown Corp', max_length=255),
        ),
    ]
