# Generated by Django 5.0 on 2025-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0006_characterhistory_corporation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='concord_lp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
