# Generated by Django 5.0 on 2025-12-03 13:20

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0007_evecharacter_concord_lp_evecharacter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecharacter',
            name='access_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='refresh_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
