# Generated by Django 5.0 on 2025-12-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0008_alter_evecharacter_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.IntegerField()),
                ('old_level', models.IntegerField()),
                ('new_level', models.IntegerField()),
                ('old_sp', models.BigIntegerField()),
                ('new_sp', models.BigIntegerField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_history', to='pilot_data.evecharacter')),
            ],
        ),
    ]
