# Generated by Django 5.0 on 2025-12-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0009_skillhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.IntegerField(db_index=True)),
                ('value', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pilot_data.itemtype')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'attribute_id'], name='pilot_data__item_id_ac6e27_idx')],
                'unique_together': {('item', 'attribute_id')},
            },
        ),
    ]
