# Generated by Django 5.0 on 2025-12-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0010_typeattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esiheadercache',
            name='expires',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
