# Generated by Django 5.0 on 2025-12-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0011_alter_esiheadercache_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
