# Generated by Django 5.0 on 2025-12-06 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0012_evecharacter_is_online_evecharacter_last_login_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.IntegerField(db_index=True)),
                ('is_default', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='pilot_data.itemtype')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'effect_id'], name='pilot_data__item_id_2ce38d_idx')],
                'unique_together': {('item', 'effect_id')},
            },
        ),
    ]
