# Generated by Django 5.0 on 2025-12-08 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0013_typeeffect'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('attribute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitAnalysisRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Order of importance (higher first)')),
                ('comparison_logic', models.CharField(choices=[('higher', 'Higher is Better'), ('lower', 'Lower is Better'), ('match', 'Must Match Exactly')], default='higher', max_length=20)),
                ('tolerance_percent', models.FloatField(default=0.0, help_text='Percentage difference allowed before flagging as downgrade')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot_data.attributedefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_rules', to='pilot_data.itemgroup')),
            ],
            options={
                'ordering': ['group', '-priority'],
                'unique_together': {('group', 'attribute')},
            },
        ),
    ]
