# Generated by Django 5.0 on 2025-12-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0014_attributedefinition_fitanalysisrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='group_id',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='group',
            field=models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='pilot_data.itemgroup'),
        ),
    ]
