# Generated by Django 5.0 on 2025-12-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0015_remove_itemtype_group_id_itemtype_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='x_up_visible',
            field=models.BooleanField(default=True),
        ),
    ]
