# Generated by Django 5.0 on 2025-12-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0016_evecharacter_x_up_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='srp_config', to='pilot_data.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='CorpWalletJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.BigIntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('context_id', models.BigIntegerField(blank=True, null=True)),
                ('context_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('description', models.TextField()),
                ('first_party_id', models.IntegerField(null=True)),
                ('second_party_id', models.IntegerField(null=True)),
                ('reason', models.TextField(blank=True)),
                ('ref_type', models.CharField(max_length=50)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('division', models.IntegerField(db_index=True, default=1)),
                ('first_party_name', models.CharField(blank=True, max_length=255)),
                ('second_party_name', models.CharField(blank=True, max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='pilot_data.srpconfiguration')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'division'], name='pilot_data__date_5be29d_idx'), models.Index(fields=['ref_type'], name='pilot_data__ref_typ_188743_idx')],
            },
        ),
    ]
