# Generated by Django 5.0 on 2025-12-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_data', '0017_srpconfiguration_corpwalletjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpwalletjournal',
            name='custom_category',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='corpwalletjournal',
            index=models.Index(fields=['custom_category'], name='pilot_data__custom__935596_idx'),
        ),
    ]
