# Generated by Django 5.0 on 2025-12-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot_data", "0018_corpwalletjournal_custom_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="last_online_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
