# Generated by Django 5.0 on 2025-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot_data", "0019_evecharacter_last_online_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="granted_scopes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
