# Generated by Django 5.0 on 2026-01-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot_data", "0020_evecharacter_granted_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="include_lp_in_aggregate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="include_sp_in_aggregate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="include_wallet_in_aggregate",
            field=models.BooleanField(default=True),
        ),
    ]
