# Generated by Django 5.0 on 2025-12-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot_data", "0020_evecharacter_granted_scopes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evecharacter",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="token_expires",
        ),
    ]
