# Generated by Jules for Aggregate Toggles

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("pilot_data", "0021_remove_evecharacter_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecharacter",
            name="include_wallet_in_aggregate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="include_lp_in_aggregate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="include_sp_in_aggregate",
            field=models.BooleanField(default=True),
        ),
    ]
