# Generated by Django 5.0 on 2025-12-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot_data", "0022_evecharacter_aggregates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evecharacter",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="evecharacter",
            name="last_login_at",
        ),
    ]
